name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 🐳 Construir a imagem Docker
        run: docker build . --file ./Dockerfile --tag mage2tools:$(date +%s)
