name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'projects/mage2tools/**'
    paths-ignore:
      - 'projects/mage2tools/data/products/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'projects/mage2tools/**'
    paths-ignore:
      - 'projects/mage2tools/data/products/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file ./projects/mage2tools/Dockerfile --tag lionn-mage2tools:$(date +%s)
